INSERT INTO sports(id, name, english_name, code, icon) values (1, 'Điền kinh', 'Athletics', 'AT', 'sport/Sao_La_DienKinh1.png'),
(2, 'Thể dục', 'Gymnastics', 'GY', 'sport/SaoLa_theducnhipdieu.png'),
(3, 'Bắn súng', 'Shooting', 'SH', 'sport/SaoLa_bansung.png'),
(4, 'Taekwondo', 'Taekwondo', 'TK', 'sport/SaoLa_taekwondo.png'),
(5, 'Đua xe đạp', 'Cycling', 'CY', 'sport/Sao_La_XeDap.png'),
(6, 'Bắn cung', 'Archery', 'AR', 'sport/Sao_La_BanCung.png'),
(7, 'Đấu kiếm', 'Fencing', 'FE', 'sport/Sao_La_DauKiem.png'),
(8, 'Judo', 'Judo', 'JU', 'sport/Sao_La_Judo.png'),
(9, 'Wushu', 'Wushu', 'WU', 'sport/Sao_La_Wushu.png'),
(10, 'Pencak Silat', 'Pencak Silat', 'PS', 'sport/SaoLa_pencak.png'),
(11, 'Vật', 'Wrestling', 'WR', 'sport/SaoLa_vat.png'),
(12, 'Quyền anh', 'Boxing', 'BX', 'sport/Sao_La_Boxing.png'),
(13, 'Karate', 'Karate', 'KR', 'sport/SaoLa_karate.png'),
(14, 'Vovinam', 'Vovinam', 'VV', 'sport/Sao_La_VoViNam.png'),
(15, 'Khiêu vũ thể thao', 'Dancesport', 'DS', 'sport/SaoLa_khieuvu.png'),
(16, 'Kurash', 'Kurash', 'KU', 'sport/SaoLa_Kurash.png'),
(17, 'Muay', 'Muay', 'MU', 'sport/SaoLa_muay.png'),
(18, 'Kickboxing', 'Kickboxing', 'KB', 'sport/SaoLa_Kichbox.png'),
(19, '3 Môn phối hợp', 'Triathlon and Duathlon', 'TD', ''),
(20, 'Jujitsu', 'Jujitsu', 'JU', 'sport/SaoLa_judo.png'),
(21, 'Bơi', 'Swimming', 'SW', 'sport/Sao_La_boi.png'),
(22, 'Lặn', 'Diving', 'DV', 'sport/SaoLa_Lan.png'),
(23, 'Cử tạ', 'Weightlifting', 'WL', 'sport/Sao_La_Cuta.png'),
(24, 'Rowing', 'Rowing','RO', 'sport/SaoLa_Rowing.png'),
(25, 'Canoeing & Kayak', 'Canoeing & Kayak', 'CK', 'sport/Sao_La_Kayak.png'),
(26, 'Bóng đá', 'Football', 'FB', 'sport/Sao_La_DaBong.png'),
(27, 'Bóng chuyền', 'Voleyball', 'VO', 'sport/Sao_La_BongChuyen.png'),
(28, 'Bóng ném', 'Handball', 'HB', 'sport/SaoLa_bongnem.png'),
(29, 'Bóng rổ', 'Basketball', 'BB', 'sport/Sao_La_BongRo.png'),
(30, 'Cầu mây', 'Sepak Takraw', 'ST', 'sport/SaoLa_caumay.png'),
(31, 'Thể hình', 'Bodybuilding', 'BO', 'sport/Sao_La_TheHinh.png'),
(32, 'Billiard', 'Billiard', 'BI', 'sport/Sao_La_BiA.png'),
(33, 'Petanque', 'Petanque', 'PE', 'sport/Sao_La_BiSat.png'),
(34, 'Cờ vua và cờ tướng', 'Chess & Chinese chess', 'CC', ''),
(35, 'Bóng bàn', 'Table tennis', 'TT', 'sport/Sao_La_BongBan.png'),
(36, 'Cầu lông', 'Badminton','BA', 'sport/SaoLa_caulong.png'),
(37, 'Quần vợt', 'Tennis', 'TE', 'sport/Sao_La_Tennis.png'),
(38, 'Golf', 'Golf', 'GO', 'sport/Sao_La_Golf.png'),
(39, 'Bowling', 'Bowling','BL', 'sport/SaoLa_Bowling.png'),
(40, 'Thể thao điện tử', 'Esport', 'ES', 'sport/SaoLa_esport.png')	