INSERT INTO sports(id, name, english_name, icon) values 
(1, 'Điền kinh', 'Athletics', '1.png'),
(2, 'Thể dục', 'Gymnastics', '2.png'),
(3, 'Bắn súng', 'Shooting', '3.png'),
(4, 'Taekwondo', 'Taekwondo', '4.png'),
(5, 'Đua xe đạp', 'Cycling', '5.png'),
(6, 'Bắn cung', 'Archery', '6.png'),
(7, 'Đấu kiếm', 'Fencing', '7.png'),
(8, 'Judo', 'Judo', '8.png'),
(9, 'Wushu', 'Wushu', '9.png'),
(10, 'Pencak Silat', 'Pencak Silat', '10.png'),
(11, 'Vật', 'Wrestling', '11.png'),
(12, 'Quyền anh', 'Boxing', '12.png'),
(13, 'Karate', 'Karate', '13.png'),
(14, 'Vovinam', 'Vovinam', '14.png'),
(15, 'Khiêu vũ thể thao', 'Dancesport', '15.png'),
(16, 'Kurash', 'Kurash', '16.png'),
(17, 'Muay', 'Muay', '17.png'),
(18, 'Kickboxing', 'Kickboxing', '18.png'),
(19, '3 Môn phối hợp', 'Triathlon and Duathlon', '19.png'),
(20, 'Jujitsu', 'Jujitsu', '20.png'),
(21, 'Bơi', 'Swimming', '21.png'),
(22, 'Lặn', 'Diving', '22.png'),
(23, 'Cử tạ', 'Weightlifting', '23.png'),
(24, 'Rowing', 'Rowing', '24.png'),
(25, 'Canoeing & Kayak', 'Canoeing & Kayak', '25.png'),
(26, 'Bóng đá', 'Football', '26.png'),
(27, 'Bóng chuyền', 'Voleyball', '27.png'),
(28, 'Bóng ném', 'Handball', '28.png'),
(29, 'Bóng rổ', 'Basketball', '29.png'),
(30, 'Cầu mây', 'Sepak Takraw', '30.png'),
(31, 'Thể hình', 'Bodybuilding', '31.png'),
(32, 'Billiard', 'Billiard', '32.png'),
(33, 'Petanque', 'Petanque', '33.png'),
(34, 'Cờ vua và cờ tướng', 'Chess & Chinese chess', '34.png'),
(35, 'Bóng bàn', 'Table tennis', '35.png'),
(36, 'Cầu lông', 'Badminton', '36.png'),
(37, 'Quần vợt', 'Tennis', '37.png'),
(38, 'Golf', 'Golf', '38.png'),
(39, 'Bowling', 'Bowling', '39.png'),
(40, 'Thể thao điện tử', 'Esport', '40.png')							