INSERT INTO m_countries(country_code_3_digits, name, flag_url) VALUES
("AFG", "Afghanistan", "flags/Afghanistan.png"),
("ALB", "Albania", "flags/Albania.png"),
("ALG", "Algeria", "flags/Algeria.png"),
("ASA", "American Samoa", "flags/American Samoa.png"),
("AND", "Andorra", "flags/Andorra.png"),
("ANG", "Angola", "flags/Angola.png"),
("AGL", "Anguilla", "flags/Anguilla.png"),
("ATA", "Antarctica", NULL),
("ANT", "Antigua and Barbuda", "flags/Antigua and Barbuda.png"),
("ARG", "Argentina", "flags/Argentina.png"),
("ARM", "Armenia", "flags/Armenia.png"),
("ARU", "Aruba", "flags/Aruba.png"),
("AUS", "Australia", "flags/Australia.png"),
("AUT", "Cambodia", "flags/Cambodia.png"),
("AZE", "Azerbaijan", "flags/Azerbaijan.png"),
("BAH", "Bahamas", "flags/Bahamas.png"),
("BRN", "Bahrain", "flags/Bahrain.png"),
("BAN", "Bangladesh", "flags/Bangladesh.png"),
("BAR", "Barbados", "flags/Barbados.png"),
("BLR", "Belarus", "flags/Belarus.png"),
("BEL", "Belgium", "flags/Belgium.png"),
("BIZ", "Belize", "flags/Belize.png"),
("BEN", "Benin", "flags/Benin.png"),
("BER", "Bermuda", "flags/Bermuda.png"),
("BHU", "Bhutan", "flags/Bhutan.png"),
("BOL", "Bolivia", "flags/Bolivia.png"),
("BIH", "Bosnia and Herzegovina", "flags/Bosnia and Herzegovina.png"),
("BOT", "Botswana", "flags/Botswana.png"),
("BVT", "Bouvet Island", "flags/Bouvet Island.png"),
("BRA", "Brazil", "flags/Brazil.png"),
("IOT", "British Indian Ocean Territory", "flags/British Indian Ocean Territory.png"),
("BRU", "Brunei Darussalam", "flags/Brunei Darussalam.png"),
("BUL", "Bulgaria", "flags/Bulgaria.png"),
("BUR", "Burkina Faso", "flags/Burkina Faso.png"),
("BMA", "Burma", "flags/Burma.png"),
("BIR", "Burundi", "flags/Burundi.png"),
("CAM", "Cambodia", "flags/Cambodia.png"),
("CMR", "Cameroon", "flags/Cameroon.png"),
("CAN", "Canada", "flags/Canada.png"),
("CPV", "Cape Verde", "flags/Cape Verde.png"),
("CAY", "Cayman Islands", "flags/Cayman Islands.png"),
("CAF", "Central African Republic", "flags/Central African Republic.png"),
("CHA", "Chad", "flags/Chad.png"),
("CHI", "Chile", "flags/Chile.png"),
("CHN", "China", "flags/China.png"),
("TPE", "Chinese Taipei", "flags/Chinese Taipei.png"),
("CXR", "Christmas Island", "flags/Christmas Island.png"),
("CCK", "Cocos (Keeling) Islands", "flags/Cocos (Keeling) Islands.png"),
("COL", "Colombia", "flags/Colombia.png"),
("COM", "Comoros", "flags/Comoros.png"),
("CGO", "Congo", "flags/Congo.png"),
("COD", "Congo, The Democratic Republic of the", "flags/Congo, The Democratic Republic of the.png"),
("COK", "Cook Islands", "flags/Cook Islands.png"),
("CRC", "Costa Rica", "flags/Costa Rica.png"),
("CIV", "Cote D'Ivoire", "flags/Cote D'Ivoire.png"),
("CRO", "Croatia", "flags/Croatia.png"),
("CUB", "Cuba", "flags/Cuba.png"),
("CYP", "Cyprus", "flags/Cyprus.png"),
("CZE", "Czech Republic", "flags/Czech Republic.png"),
("DEN", "Denmark", "flags/Denmark.png"),
("DJI", "Djibouti", "flags/Djibouti.png"),
("DMA", "Dominica", "flags/Dominica.png"),
("DOM", "Dominican Republic", "flags/Dominican Republic.png"),
("ECU", "Ecuador", "flags/Ecuador.png"),
("EGY", "Egypt", "flags/Egypt.png"),
("ESA", "El Salvador", "flags/El Salvador.png"),
("GEQ", "Equatorial Guinea", "flags/Equatorial Guinea.png"),
("ERI", "Eritrea", "flags/Eritrea.png"),
("EST", "Estonia", "flags/Estonia.png"),
("ETH", "Ethiopia", "flags/Ethiopia.png"),
("FAI", "Falkland Islands", "flags/Falkland Islands.png"),
("FRO", "Faroe Islands", "flags/Faroe Islands.png"),
("FIJ", "Fiji", "flags/Fiji.png"),
("FIN", "Finland", "flags/Finland.png"),
("FRA", "France", "flags/France.png"),
("GUF", "French Guiana", "flags/French Guiana.png"),
("PYF", "French Polynesia", "flags/French Polynesia.png"),
("FQH", "French Southern Territories", "flags/French Southern Territories.png"),
("GAB", "Gabon", "flags/Gabon.png"),
("GAM", "Gambia", "flags/Gambia.png"),
("GEO", "Georgia", "flags/Georgia.png"),
("GER", "Germany", "flags/Germany.png"),
("GHA", "Ghana", "flags/Ghana.png"),
("GIB", "Gibraltar", "flags/Gibraltar.png"),
("GRE", "Greece", "flags/Greece.png"),
("GRL", "Greenland", "flags/Greenland.png"),
("GRN", "Grenada", "flags/Grenada.png"),
("GLP", "Guadeloupe", "flags/Guadeloupe.png"),
("GUM", "Guam", "flags/Guam.png"),
("GUA", "Guatemala", "flags/Guatemala.png"),
("GUI", "Guinea", "flags/Guinea.png"),
("GBS", "Guinea-Bissau", "flags/Guinea-Bissau.png"),
("GUY", "Guyana", "flags/Guyana.png"),
("HAI", "Haiti", "flags/Haiti.png"),
("HDM", "Heard Island and Mcdonald Islands", NULL),
("VAT", "Holy See (Vatican City State)", "flags/Holy See (Vatican City State).png"),
("HON", "Honduras", "flags/Honduras.png"),
("HKG", "Hong Kong, China", "flags/Hong Kong, China.png"),
("HUN", "Hungary", "flags/Hungary.png"),
("ISL", "Iceland", "flags/Iceland.png"),
("IND", "India", "flags/India.png"),
("INA", "Indonesia", "flags/Indonesia.png"),
("IRI", "Iran, Islamic Republic of", "flags/Iran, Islamic Republic of.png"),
("IRQ", "Iraq", "flags/Iraq.png"),
("IRL", "Ireland", "flags/Ireland.png"),
("ISR", "Israel", "flags/Israel.png"),
("ITA", "Italy", "flags/Italy.png"),
("JAM", "Jamaica", "flags/Jamaica.png"),
("JPN", "Japan", "flags/Japan.png"),
("JOR", "Jordan", "flags/Jordan.png"),
("KAZ", "Kazakhstan", "flags/Kazakhstan.png"),
("KEN", "Kenya", "flags/Kenya.png"),
("KIR", "Kiribati", "flags/Kiribati.png"),
("PRK", "Korea, Democratic People's Republic of", "flags/Korea, Democratic People's Republic of.png"),
("KOR", "Korea, Republic of", "flags/Korea, Republic of.png"),
("KUW", "Kuwait", "flags/Kuwait.png"),
("KGZ", "Kyrgyzstan", "flags/Kyrgyzstan.png"),
("LAO", "Lao People's Democratic Republic", "flags/Lao People's Democratic Republic.png"),
("LAT", "Latvia", "flags/Latvia.png"),
("LIB", "Lebanon", "flags/Lebanon.png"),
("LES", "Lesotho", "flags/Lesotho.png"),
("LBR", "Liberia", "flags/Liberia.png"),
("LBA", "Libyan Arab Jamahiriya", "flags/Libyan Arab Jamahiriya.png"),
("LIE", "Liechtenstein", "flags/Liechtenstein.png"),
("LTU", "Lithuania", "flags/Lithuania.png"),
("LUX", "Luxembourg", "flags/Luxembourg.png"),
("MAC", "Macau, China", "flags/Macau, China.png"),
("MKD", "Macedonia, The Former Yugoslav Republic", "flags/Macedonia, The Former Yugoslav Republic.png"),
("MAD", "Madagascar", "flags/Madagascar.png"),
("MAW", "Malawi", "flags/Malawi.png"),
("MAS", "Malaysia", "flags/Malaysia.png"),
("MDV", "Maldives", "flags/Maldives.png"),
("MLI", "Mali", "flags/Mali.png"),
("MLT", "Malta", "flags/Malta.png"),
("MHL", "Marshall Islands", "flags/Marshall Islands.png"),
("MTO", "Martinique", "flags/Martinique.png"),
("MTN", "Mauritania", "flags/Mauritania.png"),
("MRI", "Mauritius", "flags/Mauritius.png"),
("MYT", "Mayotte", NULL),
("MEX", "Mexico", "flags/Mexico.png"),
("FSM", "Micronesia, Federated States of", "flags/Micronesia, Federated States of.png"),
("MDA", "Moldova, Republic of", "flags/Moldova, Republic of.png"),
("MON", "Monaco", "flags/Monaco.png"),
("MGL", "Mongolia", "flags/Mongolia.png"),
("MNT", "Montserrat", "flags/Montserrat.png"),
("MAR", "Morocco", "flags/Morocco.png"),
("MOZ", "Mozambique", "flags/Mozambique.png"),
("MYA", "Myanmar", "flags/Myanmar.png"),
("NAM", "Namibia", "flags/Namibia.png"),
("NRU", "Nauru", "flags/Nauru.png"),
("NEP", "Nepal", "flags/Nepal.png"),
("NED", "Netherlands", "flags/Netherlands.png"),
("AHO", "Netherlands Antilles", "flags/Netherlands Antilles.png"),
("NCL", "New Caledonia", NULL),
("NHB", "New Hebrides", NULL),
("NZL", "New Zealand", "flags/New Zealand.png"),
("NCA", "Nicaragua", "flags/Nicaragua.png"),
("NIG", "Niger", "flags/Niger.png"),
("NGR", "Nigeria", "flags/Nigeria.png"),
("NIU", "Niue", "flags/Niue.png"),
("NFI", "Norfolk Island", "flags/Norfolk Island.png"),
("MNP", "Northern Mariana Islands", "flags/Northern Mariana Islands.png"),
("NOR", "Norway", "flags/Norway.png"),
-- ("ZOK", "Not listed", NULL),
("OMA", "Oman", "flags/Oman.png"),
("PCI", "Pacific Islands (Trust Territory)", "flags/Pacific Islands (Trust Territory).png"),
("PAK", "Pakistan", "flags/Pakistan.png"),
("PLW", "Palau", "flags/Palau.png"),
("PLE", "Palestinian Territory", "flags/Palestinian Territory.png"),
("PAN", "Panama", "flags/Panama.png"),
("PNG", "Papua New Guinea", "flags/Papua New Guinea.png"),
("PAR", "Paraguay", "flags/Paraguay.png"),
("PER", "Peru", "flags/Peru.png"),
("PHI", "Philippines", "flags/Philippines.png"),
("PCN", "Pitcairn", "flags/Pitcairn.png"),
("POL", "Poland", "flags/Poland.png"),
("ZOC", "Polynesia", "flags/Polynesia.png"),
("POR", "Portugal", "flags/Portugal.png"),
("PUR", "Puerto Rico", "flags/Puerto Rico.png"),
("QAT", "Qatar", "flags/Qatar.png"),
("REU", "Reunion", "flags/Reunion.png"),
("ROM", "Romania", "flags/Romania.png"),
("RUS", "Russian Federation", "flags/Russian Federation.png"),
("RWA", "Rwanda", "flags/Rwanda.png"),
("SHE", "Saint Helena", "flags/Saint Helena.png"),
("SKN", "Saint Kitts and Nevis", "flags/Saint Kitts and Nevis.png"),
("LCA", "Saint Lucia", "flags/Saint Lucia.png"),
("SPM", "Saint Pierre and Miquelon", "flags/Saint Pierre and Miquelon.png"),
("VIN", "Saint Vincent and the Grenadines", "flags/Saint Vincent and the Grenadines.png"),
("SAM", "Samoa", "flags/Samoa.png"),
("SMR", "San Marino", "flags/San Marino.png"),
("STP", "Sao Tome and Principe", "flags/Sao Tome and Principe.png"),
("KSA", "Saudi Arabia", "flags/Saudi Arabia.png"),
("SEN", "Senegal", "flags/Senegal.png"),
("SCG", "Serbia and Montenegro", "flags/Serbia and Montenegro.png"),
("SEY", "Seychelles", "flags/Seychelles.png"),
("SLE", "Sierra Leone", "flags/Sierra Leone.png"),
("SIN", "Singapore", "flags/Singapore.png"),
("SVK", "Slovakia", "flags/Slovakia.png"),
("SLO", "Slovenia", "flags/Slovenia.png"),
("SOL", "Solomon Islands", "flags/Solomon Islands.png"),
("SOM", "Somalia", "flags/Somalia.png"),
("RSA", "South Africa", "flags/South Africa.png"),
("SGS", "South Georgia and the South Sandwich Islands", "flags/South Georgia and the South Sandwich Islands.png"),
("ESP", "Spain", "flags/Spain.png"),
("SRI", "Sri Lanka", "flags/Sri Lanka.png"),
("SUD", "Sudan", "flags/Sudan.png"),
("SUR", "Suriname", "flags/Suriname.png"),
("SIM", "Svalbard and Jan Mayen", "flags/Svalbard and Jan Mayen.png"),
("SWZ", "Swaziland", "flags/Swaziland.png"),
("SWE", "Sweden", "flags/Sweden.png"),
("SUI", "Switzerland", "flags/Switzerland.png"),
("SYR", "Syrian Arab Republic", "flags/Syrian Arab Republic.png"),
("TJK", "Tajikistan", "flags/Tajikistan.png"),
("TAN", "Tanzania, United Republic of", "flags/Tanzania, United Republic of.png"),
("THA", "Thailand", "flags/Thailand.png"),
("TLS", "Timor-Leste", "flags/Timor-Leste.png"),
("TOG", "Togo", "flags/Togo.png"),
("TKL", "Tokelau", "flags/Tokelau.png"),
("TGA", "Tonga", "flags/Tonga.png"),
("TRI", "Trinidad and Tobago", "flags/Trinidad and Tobago.png"),
("TUN", "Tunisia", "flags/Tunisia.png"),
("TUR", "Turkey", "flags/Turkey.png"),
("TKM", "Turkmenistan", "flags/Turkmenistan.png"),
("TKS", "Turks and Caicos Islands", "flags/Turks and Caicos Islands.png"),
("TUV", "Tuvalu", "flags/Tuvalu.png"),
("UGA", "Uganda", "flags/Uganda.png"),
("UKR", "Ukraine", "flags/Ukraine.png"),
("UAE", "United Arab Emirates", "flags/United Arab Emirates.png"),
("GBR", "United Kingdom of Great Britain & N. Ireland", "flags/United Kingdom of Great Britain & N. Ireland.png"),
("ZON", "United Nations Organisation", "flags/United Nations Organisation.png"),
("USA", "United States", "flags/United States.png"),
("URU", "Uruguay", "flags/Uruguay.png"),
("UZB", "Uzbekistan", "flags/Uzbekistan.png"),
("VAN", "Vanuatu", "flags/Vanuatu.png"),
("VEN", "Venezuela", "flags/Venezuela.png"),
("VIE", "Vietnam", "flags/Vietnam.png"),
("ISB", "Virgin Islands, British", "flags/Virgin Islands, British.png"),
("ISV", "Virgin Islands, U. S.", "flags/Virgin Islands, U. S..png"),
("WAL", "Wales", "flags/Wales.png"),
("WLF", "Wallis and Futuna", "flags/Wallis and Futuna.png"),
("ESH", "Western Sahara", NULL),
("YEM", "Yemen", "flags/Yemen.png"),
("YUG", "Yugoslavia", NULL),
("ZAI", "Zaire", NULL),
("ZAM", "Zambia", "flags/Zambia.png"),
("ZIM", "Zimbabwe", "flags/Zimbabwe.png");
