INSERT INTO sport_disciplines (sport_id, id, name, english_name, icon) values (1, '1', 'Chạy', 'Athletic race', NULL),
(1, '2', 'Chạy vượt CNV', 'Steeplechase', NULL),
(1, '3', 'Marathon', 'Marathon', NULL),
(1, '4', 'Đi bộ', 'Racewalking', NULL),
(1, '5', 'Nhảy', 'Jumping', NULL),
(1, '6', 'Ném xa', 'Throwing', NULL),
(1, '7', 'Nội dung hỗn hợp', 'Mixed discipline', NULL),
(2, '8', 'Thể dục dụng cụ', 'Artistic', NULL),
(2, '9', 'Thể dục nghệ thuật', 'Rhythmic', NULL),
(2, '10', 'Thể dục Aerobic', 'Aerobic', NULL),
(3, '11', 'Súng ngắn', 'Pistol shooting', NULL),
(3, '12', 'Súng trường', 'Rifle shooting', NULL),
(3, '13', 'Đĩa bay', 'Trap shooting', NULL),
(4, '14', 'Biểu diễn', 'Poomsae', NULL),
(4, '15', 'Đối kháng', 'Kyorugi', NULL),
(5, '16', 'Xe đạp đường trường', 'Road cycling', NULL),
(5, '17', 'Xe đạp địa hình', 'Moutain cycling', NULL),
(6, '18', 'Cung 1 dây', 'Recurve', NULL),
(6, '19', 'Cung 3 dây', 'Compound', NULL),
(7, '20', 'Kiếm chém', 'Sabre', NULL),
(7, '21', 'Kiếm ba cạnh', 'épée', NULL),
(7, '22', 'Kiếm liễu', 'Foil', NULL),
(8, '23', 'Biểu diễn', 'Kata', NULL),
(8, '24', 'Đối kháng', 'Combat', NULL),
(9, '25', 'Biểu diễn', 'Taolu', NULL),
(9, '26', 'Đối kháng', 'Sanda', NULL),
(10, '27', 'Biểu diễn', 'Seni', NULL),
(10, '28', 'Đối kháng', 'Tanding', NULL),
(11, '29', 'Vật cổ điển', 'Greco-Roman', NULL),
(11, '30', 'Vật tự do', 'Freestyle', NULL),
(12, '31', 'Boxing', 'Boxing', NULL),
(13, '32', 'Biển diễn', 'Kata', NULL),
(13, '33', 'Đối kháng', 'Kumite', NULL),
(14, '34', 'Biểu diễn', 'Artistic', NULL),
(14, '35', 'Đối kháng', 'Combat', NULL),
(15, '36', 'Khiêu vũ', 'Dance', NULL),
(16, '37', 'Đối kháng', 'Combat', NULL),
(17, '38', 'Đối kháng', 'Combat', NULL),
(18, '39', 'Lowkick', 'Lowkick', NULL),
(18, '40', 'Fullcontract', 'Fullcontract', NULL),
(19, '41', 'Triathlon', 'Triathlon', NULL),
(19, '42', 'Duathlon', 'Duathlon', NULL),
(20, '43', 'Combat', 'Combat', NULL),
(21, '44', 'Bơi tự do', 'Freestyle swimming', NULL),
(21, '45', 'Bơi ngửa', 'Backstroke swimming', NULL),
(21, '46', 'Bơi ếch', 'Breaststroke swimming', NULL),
(21, '47', 'Bơi bướm', 'Butterfly swimming', NULL),
(21, '48', 'Bơi Hỗn hợp', 'Medley swimming', NULL),
(21, '49', 'Bơi Tiếp sức tự do', 'Freestyle swimming relay', NULL),
(21, '50', 'Bơi tiếp sức hỗn hợp', 'Medley swimming relay', NULL),
(21, '51', 'Nhảy cầu', 'Diving board', NULL),
(22, '52', 'Chân vịt đôi', 'Flippers', NULL),
(22, '53', 'Vòi hơi chân vịt', 'Snorkel & flippers', NULL),
(22, '54', 'Tiếp sức vòi hơi chân vịt', 'Snorkel & flippers relay', NULL),
(23, '55', 'Cử tạ', 'Weightlifting', NULL),
(24, '56', 'Rowing', 'Rowing', NULL),
(25, '57', 'Canoeing', 'Canoeing', NULL),
(25, '58', 'Kayak', 'Kayak', NULL),
(26, '59', 'Bóng đá', 'Football', NULL),
(26, '60', 'Futsal', 'Futsal', NULL),
(27, '61', 'Trong nhà', 'Indoor voleyball', NULL),
(27, '62', 'Bãi biển', 'Beach voleyball', NULL),
(28, '63', 'Trong nhà', 'Indoor handball', NULL),
(28, '64', 'Bãi biển', 'Beach handball', NULL),
(29, '65', 'Bóng rổ', 'Basketball', NULL),
(30, '66', 'Cầu mây', 'Sepak Takraw', NULL),
(31, '67', 'Thể hình', 'Bodybuilding', NULL),
(32, '68', 'Carom', 'Carom', NULL),
(32, '69', 'Snooker', 'Snooker', NULL),
(32, '70', 'English', 'English', NULL),
(32, '71', 'Pool', 'Pool', NULL),
(33, '72', 'Petanque', 'Petanque', NULL),
(34, '73', 'Cờ vua', 'Chess', 'sport/SaoLa_covua.png'),
(34, '74', 'Cờ tướng', 'Chinese chess', 'sport/SaoLa_CoTuong.png'),
(35, '75', 'Bóng bàn', 'Table tennis', NULL),
(36, '76', 'Cầu lông', 'Badminton', NULL),
(37, '77', 'Quần vợt', 'Tennis', NULL),
(38, '78', 'Golf', 'Golf', NULL),
(39, '79', 'Bowling', 'Bowling', NULL),
(40, '80', 'Liên minh huyền thoại: Tốc chiến', 'LOL: Wid Rift-Mobile', NULL),
(40, '81', 'Liên quân Mobile', 'Arena of Valor', NULL),
(40, '82', 'PUBG Mobile', 'PUBG Mobile', NULL),
(40, '83', 'PUBG Mobile', 'PUBG Mobile', NULL),
(40, '84', 'Đấu trường sinh tồn', 'Free fire', NULL),
(40, '85', 'Liên minh huyền thoại ', 'League of Legends', NULL),
(40, '86', 'Fifa Online 4', 'Fifa Online 4', NULL),
(40, '87', 'Đột kích', 'Cross Fire', NULL),
(40, '88', 'Mobile Legends: Bang bang', 'Mobile Legends: Bang bang', NULL)	