INSERT INTO sports(name, english_name, code) VALUES
("Điền kinh", "Athletics","AT"),
("Thể dục dụng cụ", "Gymnastics", "GYM"),
("Thể dục nghệ thuật", "Art fitness", "AFI"),
("Thể dục Aerobic", "Aerobic exercise", "AEX"),
("Súng ngắn", "Pistols", "PIS"),
("Súng trường", "Rifle", "RIF"),
("Bắn đĩa bay", "Trap", "TRA"),
("Taekwondo","Taekwondo","TK"),
("Xe đạp đường trường","Road bike","RB"),
("Xe đạp địa hình","Mountain bike","MB"),
("Bắn cung","Archery","AR"),
("Đấu kiếm", "Fencing", "FE"),
("Judo", "Judo", "JD"),
("Wushu","Wushu","WU"),
("Pencak Silat","Pencak Silat","PS"),
("Vật cổ điển","Classic Wrestling","CW"),
("Vật tự do","Free Wrestling","FW"),
("Boxing", "Boxing", "BX"),
("Karate","Karate","GT"),
("Vovinam","Vovinam","VO"),
("Khiêu vũ thể thao", "Dance sports", "DS"),
("Kurash", "Kurash", "KU"),
("Muay", "Muay","MU"),
("Kick boxing", "Kick boxing", "KB"),
("Ba môn phối hợp", "Triathlon", "TL"),
("Jujitsu", "Jujitsu", "JU"),
("Bơi", "Swimming", "SWI"),
("Nhảy cầu", "Diving", "DI"),
("Lặn", "Dive", "DIV"),
("Cử tạ","Weightlifting","WL"),
("Rowing", "Rowing","RO"),
("Canoeing", "Canoeing", "CA"),
("Kayak", "Kayak", "KA"),
("Bóng đá","Football","FB"),
("Bóng chuyền","Volleyball","VB"),
("Bóng ném", "Handball", "HB"),
("Bóng rổ", "Basketball","BB"),
("Cầu mây","Sepak Takraw","ST"),
("Thể hình", "Fitness","FI"),
("Billiards & Snooker", "Billiards & Snooker","BS"),
("Petanque", "Petanque","PET"),
("Cờ vua","Chess","CH"),
("Cờ tướng","Chess","CHE"),
("Bóng bàn","Table Tennis","TT"),
("Cầu lông", "Badminton", "BD"),
("Quần vợt", "Tennis","TE"),
("Golf", "Golf", "GO"),
("Bowling", "Bowling", "BL"),
("Thể Thao Điện Tử - Esports", "Esports", "ES")
