INSERT INTO m_functions(card_template_id,organization_id,sub_code,name,code,english_name, is_staff, is_volunteer) VALUES
("1","1","OCA","Chủ tịch","A01","President", 1, 1),
("1","1","OCA","Phó Chủ tịch","A02","Vice President", 1, 1),
("1","1","OCA","Tổng Thư ký","A03","Secretary-General", 1, 1),
("1","1","OCA","Chủ tịch danh dự","A04","Honorary President", 1, 1),
("1","1","OCA","Phó Chủ tịch danh dự","A05","Honorary Vice President", 1, 1),
("1","1","OCA","Cố vấn","A06","Advisors", 1, 1),
("1","1","OCA","Trưởng Ban Thường trực","A07","Chairman of Standing Committee", 1, 1),
("1","1","OCA","Trưởng Ban Điều phối","A08","Chairman of Coordination Committee", 1, 1),
("1","1","OCA","Tổng Giám đốc","A09","Director General", 1, 1),
("1","1","OCA","Giám đốc Chuyên môn","A10","Technical Director", 1, 1),
("1","1","OCA","Thành viên EB","A11","EB Members", 1, 1),
("1","1","OCA","Khách mời đi cùng","A12","Accompanying Guest", 1, 1),
("2","3","NOC","Chủ tịch","A21","President", 1, 1),
("2","3","NOC","Tổng Thư ký","A22","Secretary General", 1, 1),
("2","3","NOC","Khách NOC (VIP được mời bởi NOC)","A23","NOC Guest (VIP invited by NOC)", 1, 1),
("2","3","NOC","Đại sứ NOC","A24","NOC Ambassador", 1, 1),
("2","3","NOC","Nhân viên","A25","Entourage", 1, 1),
("2","3","NOC","Bảo vệ hộ tống","A26","Guard escort", 1, 1),
("2","3","NOC","Khách mời đi cùng","A27","Accompanying Guest", 1, 1),
("3","2","NOC","Chủ tịch","A31","President", 1, 1),
("3","2","IOC","Phó Chủ tịch","A32","Vice President", 1, 1),
("3","2","IOC","Tổng Thư ký","A33","Secretary General", 1, 1),
("3","2","IOC","Chủ tịch Danh dự","A34","Honorary President", 1, 1),
("3","2","IOC","Thành viên Điều hành","A35","Executive Members", 1, 1),
("3","2","IOC","Tổng Giám đốc","A36","Director General", 1, 1),
("3","2","IOC","Khách mời đi cùng","A37","Accompanying Guest", 1, 1),
("4","4","IF","Chủ tịch","A41","President", 1, 1),
("4","4","IF","Tổng Thư ký","A42","Secretary-General", 1, 1),
("4","4","IF","Khách mời đi cùng","A43","Accompanying Guest", 1, 1),
("4","5","AF","Chủ tịch","A44","President", 1, 1),
("4","5","AF","Tổng Thư ký","A45","Secretary-General", 1, 1),
("4","5","AF","Khách mời đi cùng","A46","Accompanying Guest", 1, 1),
("4","9","WADA","Trưởng Ban","A51","Chairman", 1, 1),
("4","9","WADA","Tổng Giám đốc","A52","Director General", 1, 1),
("4","9","WADA","Giám đốc","A53","Director", 1, 1),
("4","9","WADA","Khách mời đi cùng","A54","Accompanying Guest", 1, 1),
("4","11","SC","Trưởng Ban","A61","Chairman", 2, 1),
("4","11","SC","Phó Trưởng Ban","A62","Vice Chairman", 2, 1),
("4","11","SC","Thành viên","A63","Member", 2, 1),
("4","12","COC","Trưởng Ban","A64","Chairman", 2, 1),
("4","12","COC","Phó Trưởng Ban","A65","Vice Chairman", 2, 1),
("4","7","XSGOC","Trưởng Ban","A71","Chairman", 1, 1),
("4","7","XSGOC","Phó Trưởng Ban","A72","Vice Chairman", 1, 1),
("4","7","XSGOC","Thành viên","A73","Member", 1, 1),
("5",null,null,"Cán bộ thành viên","A81","Staff members", 1, 1),
("5",null,null,"Thành viên Ban Thường trực","A82","Member of the Standing Committee", 1, 1),
("5",null,null,"Đại lý tiếp thị","A83","Marketing agent", 1, 1),
("5",null,null,"Nhà chuyên môn","A84","Specialist", 1, 1),
("6","3","NOC","Trưởng đoàn","B01","Team manager", 1, 1),
("6","9","WADA","Thành viên","B11","Member", 1, 1),
("6","2","IOC","Cán bộ thành viên","B21","Staff members", 1, 1),
("6","4","IF","Đại biểu chuyên môn","B31","Professional delegates", 1, 1),
("6","4","IF","Thành viên Ban Điều hành","B32","Member of the Executive Board", 1, 1),
("6","4","IF","Khách mời kèm theo của TD","B33","Attached guests of TD", 1, 1),
("6","5","AF","Đại biểu chuyên môn","B34","Professional delegates", 1, 1),
("6","5","AF","Thành viên Ban Điều hành","B35","Member of the Executive Board", 1, 1),
("6","5","AF","Khách mời kèm theo của TD","B36","Attached guests of TD", 1, 1),
("6","12","COC","Thành viên","B41","Member", 2, 1),
("6","12","COC","Trưởng Tiểu ban","B42","Head of the Subcommittee", 2, 1),
("6","12","COC","Phó trưởng Tiểu ban","B43","Deputy Head of the Subcommittee", 2, 1),
("6","13","LOC","Trưởng Ban","B44","Chairman", 2, 1),
("6","13","LOC","Phó Trưởng Ban","B45","Vice Chairman", 2, 1),
("6","10","NF","Chủ tịch","B46","President", 1, 1),
("6","10","NF","Phó Chủ tịch","B47","Vice President", 1, 1),
("6","10","NF","Tổng Thư ký","B48","General secretary", 1, 1),
("7","3","NOC","Thành viên","C01","Member", 1, 1),
("7","3","NOC","Tùy viên","C02","Attache", 1, 1),
("7","3","NOC","Phó trưởng đoàn","C03","Deputy head of the delegation", 1, 1),
("7","6","VNSGOC","Thành viên của Tiểu ban","C11","Member of the Subcommittee", 1, 1),
("7","6","VNSGOC","Thành viên","C12","Member", 1, 1),
("7","6","VNSGOC","Trưởng Tiểu ban","C13","Head of the Subcommittee", 1, 1),
("7","6","VNSGOC","Phó trưởng Tiểu ban","C14","Deputy Head of the Subcommittee", 1, 1),
("8","4","ITO","Cán bộ chuyên môn quốc tế","D01","Staff with international expertise", 1, 1),
("8","5","NTO","Cán bộ chuyên môn quốc gia","D02","National professional officer", 1, 1),
("9","3","E","Nhân viên báo chí","E01","Press staff", 1, 1),
("9","3","EP","Nhiếp ảnh gia","E02","Photographer", 1, 1),
("9","3","ET","Nhân viên hỗ trợ","E03","Support staff", 1, 1),
("10","3","RT","Phát thanh viên bản quyền","R01","Right Holding Broadcaster", 1, 1),
("10","3","RT-1","Giám sát viên","R02","Supervisor", 1, 1),
("10","3","RT-1","Nhà sản xuất","R03","Producer", 1, 1),
("10","3","RT-1","Nhà phê bình","R04","Commentator", 1, 1),
("10","3","RT-2","Nhân viên kỹ thuật","R05","Technical", 1, 1),
("10","3","RT-2","Người quay phim","R06","Cameraman", 1, 1),
("10","3","RT-3","Cán bộ hỗ trợ","R07","Support Staff", 1, 1),
("11","6","HB","Phát thanh viên nước chủ nhà","H01","Host country announcer", 1, 1),
("11","6","HB-1","Giám sát viên","H02","Supervisor", 1, 1),
("11","6","HB-1","Nhà sản xuất","H03","Producer", 1, 1),
("11","6","HB-1","Nhà phê bình","H04","Commentator", 1, 1),
("11","6","HB-2","Nhân viên kỹ thuật","H05","Technical", 1, 1),
("11","6","HB-2","Người quay phim","H06","Cameraman", 1, 1),
("11","6","HB-3","Cán bộ hỗ trợ","H07","Support Staff", 1, 1),
("13","3","NOC","Nhân viên quản lý (HQ)","F01","Management staff (HQ)", 1, 1),
("13","3","NOC","Cán Bộ","F02","Officer", 1, 1),
("13","3","NOC","Huấn luyện viên","F03","Coach", 1, 1),
("13","3","NOC","Bác sĩ","F04","Doctor", 1, 1),
("13","3","NOC","Y tá","F05","Nurse", 1, 1),
("13","3","NOC","Nhân viên mát xa","F06","Massage staff", 1, 1),
("13","3","NOC","Nhà vật lý trị liệu","F07","Physiotherapist", 1, 1),
("13","3","NOC","Đầu bếp","F08","Chef", 1, 1),
("14","3","NOC","Nhân viên bổ sung","F11","Additional staff", 1, 1),
("12","3","NOC","Vận động viên","F21","Athletes", 1, 1),
("16",null,null,"Khách mời đặc biệt","G01","The special guest", 1, 1),
("21","6","VNSGOC","Cộng sự chính thức","S01","Official partner", 1, 1),
("21","6","VNSGOC","Người bảo lãnh chính thức","S02","Official sponsor", 1, 1),
("21","6","VNSGOC","Các nhà thầu","S03","Contractors", 1, 1),
("17","12","COC","Thành viên của các Tiểu ban","P01","Members of the Subcommittees", 2, 1),
("17","12","COC","Cán bộ","P02","Officer", 2, 1),
("17","12","COC","Cán bộ phụ trách địa điểm thi đấu","P03","The officer in charge of the competition venue", 2, 1),
("17","12","COC","Nhân viên Khách sạn","P04","Hotel staff", 1, 1),
("17","12","COC","Nhân viên chuyên chở","P05","Transportation staff", 1, 1),
("18","6","VNSGOC","Phụ tá của NOC","V01","Assistant of the NOC", 1, 2),
("18","6","VNSGOC","Tình nguyện viên","V02","Volunteers",1, 2),
("18","6","VNSGOC","Các tình nguyện viên thuộc địa điểm thi đấu","V03","Volunteers from the competition site", 1, 2),
("18","6","VNSGOC","Tình nguyện viên khách sạn","V04","Volunteer hotel", 1, 2),
("18","6","VNSGOC","Tình nguyện viên chuyên chở","V05","Volunteer transportation", 1, 2),
("19","6","VNSGOC","Bảo vệ","X01","Guard", 1, 1)
