<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\ApiResourceController;
use App\Models\AuditSyncDataSetting;
use Carbon\Carbon;
use Illuminate\Http\Request;

class AuditSyncDataSettingController extends ApiResourceController
{
    //

    protected function setModel()
    {
        // TODO: Implement setModel() method.
        $this->model = new AuditSyncDataSetting();
    }
    public function index(Request $request)
    {
        return parent::index($request); // TODO: Change the autogenerated stub
    }
    public function addFilter(Request $request)
    {
        if ($request->date_range) {
            $dateRange = json_decode($request->date_range);
            $start = date('Y-m-d', strtotime($dateRange->startDate));
            $end = date('Y-m-d', strtotime($dateRange->endDate));
            $startDate =  Carbon::createFromFormat('Y-m-d', $start)->format('Y-m-d');
            $endDate = Carbon::createFromFormat('Y-m-d', $end)->format('Y-m-d');
            if ($startDate != $endDate) {
                $this->query->whereDate('updated_at', ">=", $startDate)
                    ->whereDate('updated_at', '<=', $endDate);
            } else {
                $this->query->whereDate('updated_at', $startDate);
            }
        }
    }
}
