<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\ApiResourceController;
use App\Http\Controllers\Controller;
use App\Models\User;
use Carbon\Carbon;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Log;
use OwenIt\Auditing\Models\Audit;

class AuditController extends ApiResourceController
{


    protected function setModel()
    {
        // TODO: Implement setModel() method.
        $this->model = new Audit();
    }
    public function index(Request $request)
    {
        return parent::index($request); // TODO: Change the autogenerated stub
    }

    public function addFilter()
    {
        $request = $this->request;
        $this->query->with('user')->orderBy('created_at', 'desc');
        // $this->query->whereHasMorph('user', ['App\Models\User'], function ($query) {
        //     $query->where('user_type', User::user_type['admin']);
        // });
        if ($request->event) {
            $this->query->whereIn('event', $request->event);
        }
        if ($request->date_range) {
            $dateRange = json_decode($request->date_range);
            $start = date('Y-m-d', strtotime($dateRange->startDate));
            $end = date('Y-m-d', strtotime($dateRange->endDate));
            $startDate =  Carbon::createFromFormat('Y-m-d', $start)->format('Y-m-d');
            $endDate = Carbon::createFromFormat('Y-m-d', $end)->format('Y-m-d');
            if ($startDate != $endDate) {
                $this->query->whereDate('created_at', ">=", $startDate)
                    ->whereDate('created_at', '<=', $endDate);
            } else {
                $this->query->whereDate('created_at', $startDate);
            }
        }
    }
}
