<?php

namespace App\Http\Controllers\Admin;

use App\Exports\DataExport;
use App\Http\Controllers\Controller;
use App\Http\Controllers\ApiResourceController;
use App\Models\MatchIndividualCompetitor;
use App\Models\MatchRefereeRelation;
use App\Models\CompetitorVenueEventRelation;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Log;

class CompetitorVenueEventRelationController extends ApiResourceController
{
    public function setModel()
    {
        $this->model = new CompetitorVenueEventRelation();
    }

    public function index(Request $request)
    {
        return parent::index($request); // TODO: Change the autogenerated stub
    }

    public function show(Request $request, $id)
    {
        return parent::show($request, $id); // TODO: Change the autogenerated stub
    }

    public function store(Request $request)
    {
        return parent::_store($request); // TODO: Change the autogenerated stub
    }

    public function update(Request $request, $id)
    {
        return parent::_update($request, $id); // TODO: Change the autogenerated stub
    }

    public function destroy(Request $request, $id)
    {
        return parent::destroy($request, $id); // TODO: Change the autogenerated stub
    }
    public function addFilter($request)
    {
        // if ($request->id) {
        //     $id = json_decode($request->id, true);
        //     $this->query->whereNotIn('id', $id);
        // }
        $this->query->with("venue", 'event');
    }
    public function addAppend()
    {
    }
}
