<?php

namespace App\Http\Controllers\Admin;

use App\Exports\DataExport;
use App\Models\EventGroup;
use Illuminate\Http\Request;
use App\Http\Controllers\ApiResourceController;
use App\Http\Requests\EventGroupStoreRequest;
use Illuminate\Support\Facades\Storage;
use Maatwebsite\Excel\Facades\Excel;
use Illuminate\Support\Facades\Lang;
use Illuminate\Support\Facades\DB;

class EventGroupController extends ApiResourceController
{
  protected function setModel()
  {
    $this->model = new EventGroup();
  }

  public function index(Request $request)
  {
    return parent::index($request); // TODO: Change the autogenerated stub
  }

  public function show(Request $request, $id)
  {
    return parent::show($request, $id); // TODO: Change the autogenerated stub
  }

  public function store(EventGroupStoreRequest $request)
  {
    try {
      DB::beginTransaction();
      $data = $request->only($this->model->getFillable());
      $result = $this->query->create($data);
      DB::commit();
      return $this->successResponse([
        'message' => Lang::get('response.response_message.create_result_response'),
        'id' => $result->id
      ]);
    } catch (\Exception $e) {
      DB::rollBack();
      throw $e;
      return $this->errorResponse();
    }
  }

  public function update(Request $request, $id)
  {
    $data = $request->only($this->model->getFillable());
    $item = $this->query->where('id', $id)->first();
    $item->fill($data);
    $result = $item->update();
    return $this->resultResponse($result);
  }

  public function destroy(Request $request, $id)
  {
    return parent::destroy($request, $id); // TODO: Change the autogenerated stub
  }

  public function addFilter($request)
  {
    $this->query->with('stage', 'member');
  }

  public function addAppend()
  {
    $this->query->with('stage', 'member');
  }
}
