<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\ApiResourceController;
use App\Http\Requests\SettingUpdateRequest;
use App\Models\Setting;
use Illuminate\Http\Request;

class SettingController extends ApiResourceController
{
    //
    protected function setModel()
    {
        // TODO: Implement setModel() method.
        $this->model = new Setting();
    }
    public function index(Request $request)
    {
        $data = $this->query->first();

        return $data;
    }
    public function store(Request $request)
    {
        return parent::_store($request); // TODO: Change the autogenerated stub
    }

    public function update(SettingUpdateRequest $request, $id)
    {
        if ($id == 'undefined') {
            return parent::_store($request);
        } else {
            return parent::_update($request, $id);
        }
    }
}
