<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\ApiResourceController;
use App\Models\SyncDataSetting;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use App\Models\AuditSyncDataSetting;
use App\Models\CardTemplate;
use App\Models\CompetitorVenue;
use App\Models\Country;
use App\Models\Team;
use App\Models\Regions;
use App\Models\EventTeam;
use App\Models\Functions;
use App\Models\Organization;
use App\Models\Participant;
use App\Models\Sport;
use App\Models\SportDiscipline;
use App\Models\SportDisciplineEvent;
use App\Models\CompetitorIndividualEventRelations;
use App\Models\EventTeamCompetitor;
use App\Models\EventUniformColors;
use Carbon\Carbon;
use Illuminate\Database\Query\Expression;
use Illuminate\Support\Facades\Lang;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Exception\ClientException;
use Illuminate\Support\Facades\Log;
use Illuminate\Support\Facades\Storage;
use PhpParser\ErrorHandler\Throwing;

class SyncDataController extends ApiResourceController
{
    //
    public function setModel()
    {
        $this->model = new SyncDataSetting();
    }

    public function index(Request $request)
    {
        $this->_filter($request);
        return parent::index($request); // TODO: Change the autogenerated stub
    }

    public function _filter(Request $request)
    {
    }

    public function store(Request $request)
    {
        try {
            DB::beginTransaction();
            $syncData = json_decode($request->syncData);
            foreach ($syncData as $sd) {
                $item = SyncDataSetting::query()->where('id', $sd->id)->first();
                if ($item) {
                    $item->update([
                        'api_url' => $sd->api_url,
                    ]);
                }
            }
            DB::commit();
            return $this->resultResponse($item);
        } catch (\Exception $e) {
            DB::rollBack();
            return response()->json(['error' => 'server_error', $e], 500);
        }
    }



    public function dataSyncFunctions($cardSetting_data)
    {
        $cardSetting_data = array_map(function ($item) {
            return (array) $item;
        }, $cardSetting_data);
        $cardSetting = new Functions();
        $fields = $cardSetting->getFillable();
        DB::table('m_functions')->delete();
        DB::beginTransaction();
        $value = [];
        try {
            foreach ($cardSetting_data as $key => $dt) {
                foreach ($fields as $fl) {
                    $value[$key][$fl] = $dt[$fl];
                }
                $value[$key]['id'] = $dt['id'];
            }
            DB::table('m_functions')->insert($value);
            DB::commit();
            return 1;
        } catch (\Exception $e) {
            DB::rollBack();
            $this->errorResponseSystem();
        }
    }

    public function dataSyncCategories($cardSetting_data)
    {
        $cardSetting_data = array_map(function ($item) {
            return (array) $item;
        }, $cardSetting_data);
        $cardSetting = new CardTemplate();
        $fields = $cardSetting->getFillable();
        DB::table('m_card_templates')->delete();
        DB::beginTransaction();
        $value = [];
        try {
            foreach ($cardSetting_data as $key => $dt) {
                foreach ($fields as $fl) {
                    $value[$key][$fl] = $dt[$fl];
                }
                $value[$key]['id'] = $dt['id'];
            }
            DB::table('m_card_templates')->insert($value);
            DB::commit();
            return 1;
        } catch (\Exception $e) {
            DB::rollBack();
            $this->errorResponseSystem();
        }
    }

    public function dataSyncCountry($data_country, $sport)
    {
        $data_country = array_map(function ($item) {
            return (array) $item;
        }, $data_country);
        $data_country1 = new Country();
        $fields = $data_country1->getFillable();
        //
        DB::table('m_countries')->delete();
        DB::beginTransaction();
        $country_data = [];
        Log::info($data_country);

        try {
            foreach ($data_country as $key => $dt) {
                foreach ($fields as $fl) {
                    $country_data[$key][$fl] = $dt[$fl];
                }
                $country_data[$key]['id'] = $dt['id'];
                if ($dt['flag_url']) {
                    $image = $sport->syncImage($dt['flag_url']);
                    Storage::disk('public')->put($dt['flag_url'], $image);
                }
            }
            DB::table('m_countries')->insert($country_data);
            AuditSyncDataSetting::query()->where('name', "MasterData")->update(["updated_at" => Carbon::now('Asia/Ho_Chi_Minh')]);
            DB::commit();
            return 1;
        } catch (\Exception $e) {
            $this->errorResponseSystem();
        }
    }

    public function dataOrganizations($cardSetting_data)
    {
        $cardSetting_data = array_map(function ($item) {
            return (array) $item;
        }, $cardSetting_data);
        $cardSetting = new Organization();
        $fields = $cardSetting->getFillable();
        DB::table('m_organizations')->delete();
        DB::beginTransaction();
        $value = [];
        try {
            foreach ($cardSetting_data as $key => $dt) {
                foreach ($fields as $fl) {
                    $value[$key][$fl] = $dt[$fl];
                }
                $value[$key]['id'] = $dt['id'];
                $value[$key]['created_at'] = Carbon::now('Asia/Ho_Chi_Minh');
            }
            Organization::query()->insert($value);
            AuditSyncDataSetting::query()->where('name', "CardSetting")->update(["updated_at" => Carbon::now('Asia/Ho_Chi_Minh')]);
            DB::commit();
            return 1;
        } catch (\Exception $e) {
            $this->errorResponseSystem();
        }
    }

    public function dataSyncTeam($data_team)
    {
        $data_team = array_map(function ($item) {
            return (array) $item;
        }, $data_team);
        $data_country1 = new Team();
        $fields = $data_country1->getFillable();
        //
        // DB::table('team')->delete();
        DB::beginTransaction();
        DB::statement('SET FOREIGN_KEY_CHECKS=0');
        DB::table('team')->truncate();
        DB::statement('SET FOREIGN_KEY_CHECKS=1');
        $team_data = [];
        try {
            foreach ($data_team as $key => $dt) {
                foreach ($fields as $fl) {
                    $team_data[$key][$fl] = $dt[$fl];
                }
                $team_data[$key]['id'] = $dt['id'];
            }
            DB::table('team')->insert($team_data);
            DB::commit();
            return 1;
        } catch (\Exception $e) {
            $this->errorResponseSystem();
        }
    }

    public function dataSyncVenue($venue_data)
    {
        $venue_data = array_map(function ($item) {
            return (array) $item;
        }, $venue_data);
        $venue = new CompetitorVenue();
        $fields = $venue->getFillable();
        // DB::table('competitor_venues')->delete();
        DB::beginTransaction();
        DB::statement('SET FOREIGN_KEY_CHECKS=0');
        DB::table('competitor_venues')->truncate();
        DB::statement('SET FOREIGN_KEY_CHECKS=1');
        $value = [];
        try {
            foreach ($venue_data as $key => $dt) {
                foreach ($fields as $fl) {
                    if (isset($dt[$fl])) {
                        $value[$key][$fl] = $dt[$fl];
                    }
                }
                $value[$key]['id'] = $dt['id'];
                $value[$key]['code'] = 'v' . $dt['id'];
            }
            DB::table('competitor_venues')->insert($value);
            AuditSyncDataSetting::query()->where('name', "Venue")->update(["updated_at" => Carbon::now('Asia/Ho_Chi_Minh')]);
            DB::commit();
            return 1;
        } catch (\Exception $e) {
            DB::rollBack();
            $this->errorResponseSystem();
        }
    }


    public function dataSyncRegion($data_region)
    {
        $data_region = array_map(function ($item) {
            return (array) $item;
        }, $data_region);
        $data_region1 = new Regions();
        $fields = $data_region1->getFillable();
        //
        DB::table('m_regions')->delete();
        DB::beginTransaction();
        $region_data = [];
        try {
            foreach ($data_region as $key => $dt) {
                foreach ($fields as $fl) {
                    $region_data[$key][$fl] = $dt[$fl];
                }
                $region_data[$key]['id'] = $dt['id'];
            }
            DB::table('m_regions')->insert($region_data);
            DB::commit();
            return 1;
        } catch (\Exception $e) {
            DB::rollBack();
            $this->errorResponseSystem();
        }
    }

    public function dataSyncSport($data_sport, $sport)
    {
        //fields
        $data_sport = array_map(function ($item) {
            return (array) $item;
        }, $data_sport);

        $data_sport1 = new Sport();

        $fields = $data_sport1->getFillable();
        //
        // DB::table('sports')->delete();
        DB::beginTransaction();
        DB::statement('SET FOREIGN_KEY_CHECKS=0');
        DB::table('sports')->truncate();
        DB::statement('SET FOREIGN_KEY_CHECKS=1');
        $sport_data = [];

        try {
            foreach ($data_sport as $key => $dt) {
                foreach ($fields as $fl) {
                    $sport_data[$key][$fl] = $dt[$fl];
                }
                $sport_data[$key]['id'] = $dt['id'];
                if ($dt['icon']) {
                    $image = $sport->syncImage($dt['icon']);
                    Storage::disk('public')->put($dt['icon'], $image);
                }
            }
            DB::table('sports')->insert($sport_data);
            AuditSyncDataSetting::query()->where('name', "CardSetting")->update(["updated_at" => Carbon::now('Asia/Ho_Chi_Minh')]);
            DB::commit();
            return 1;
        } catch (\Exception $e) {
            DB::rollBack();
            $this->errorResponseSystem();
        }
    }

    public function dataSyncDiscipline($data_sport, $sport)
    {
        $data_sport = array_map(function ($item) {
            return (array) $item;
        }, $data_sport);
        $result = new SportDiscipline();
        $fields = $result->getFillable();
        //
        // DB::table('sport_disciplines')->delete();
        $data_soprt_discipline = [];
        DB::beginTransaction();

        DB::statement('SET FOREIGN_KEY_CHECKS=0');
        DB::table('sport_disciplines')->truncate();
        DB::statement('SET FOREIGN_KEY_CHECKS=1');

        try {
            foreach ($data_sport as $key => $dt) {
                foreach ($fields as $fl) {
                    $data_soprt_discipline[$key][$fl] = $dt[$fl];
                }
                $data_soprt_discipline[$key]['id'] = $dt['id'];
                if ($dt['icon']) {
                    $image = $sport->syncImage($dt['icon']);
                    Storage::disk('public')->put($dt['icon'], $image);
                }
            }
            DB::table('sport_disciplines')->insert($data_soprt_discipline);
            DB::commit();
            return 1;
        } catch (\Exception $e) {
            DB::rollBack();
            $this->errorResponseSystem();
        }
    }

    public function dataSyncEvent($data_sport, $sport)
    {
        $data_sport = array_map(function ($item) {
            return (array) $item;
        }, $data_sport);
        $result = new SportDisciplineEvent();
        $fields = $result->getFillable();
        //
        // DB::table('sport_discipline_events')->delete();
        $data_soprt_discipline_events = [];
        DB::beginTransaction();

        DB::statement('SET FOREIGN_KEY_CHECKS=0');
        DB::table('sport_discipline_events')->truncate();
        DB::statement('SET FOREIGN_KEY_CHECKS=1');

        try {
            foreach ($data_sport as $key => $dt) {
                foreach ($fields as $fl) {
                    if (isset($dt[$fl])) {
                        $data_soprt_discipline_events[$key][$fl] = $dt[$fl];
                    }
                }
                $data_soprt_discipline_events[$key]['id'] = $dt['id'];
                if ($dt['icon']) {
                    $image = $sport->syncImage($dt['icon']);
                    Storage::disk('public')->put($dt['icon'], $image);
                }
            }
            DB::table('sport_discipline_events')->insert($data_soprt_discipline_events);
            DB::commit();
            return 1;
        } catch (\Exception $e) {
            DB::rollBack();
            $this->errorResponseSystem();
        }
    }

    public function syncDataCompetitorIndividual($entryByNameInvidial, $team_id)
    {
        DB::beginTransaction();
        try {
            // CompetitorIndividualEventRelations::query()->where('team_id', $team_id)->delete();
            foreach ($entryByNameInvidial as $dt) {
                DB::table('competitor_individual_event_relations')->updateOrInsert([
                    "event_id" => $dt->sport_discipline_event_id,
                    "participant_id" => $dt->personal_info_id,
                    "team_id" => $dt->team_id
                ]);
            }
            DB::commit();
            return 1;
        } catch (\Exception $e) {
            DB::rollBack();
            $this->errorResponseSystem();
        }
    }
    public function syncDataEventTeams($event_teams, $team_id)
    {
        DB::beginTransaction();
        try {
            // EventTeam::query()->where("team_id", $team_id)->delete();

            foreach ($event_teams as $dt) {
                $event_team =  EventTeam::query()->updateOrCreate(
                    [
                        "team_id" => $dt->team_id,
                        "event_id" => $dt->event_id,
                        "code" => $dt->code
                    ],
                    [
                        "name" => $dt->name,
                    ]
                );
                $team_competitors = $dt->event_team_competitor;
                $uniforms = $dt->uniforms;
                if ($uniforms) {
                    foreach ($uniforms as $eu) {
                        EventUniformColors::query()->updateOrCreate(
                            [
                                'event_team_id' => $event_team->id,
                                'team_id' => $dt->team_id,
                                'no' => $eu->no,
                                'event_id' => $eu->sport_discipline_event_id
                            ],
                            [
                                'player_shirt' => $eu->player_shirt,
                                'player_shorts' => $eu->player_shorts,
                                'goalkeeper_shirt' => $eu->goalkeeper_shirt,
                                'goalkeeper_shorts' => $eu->goalkeeper_shorts
                            ]
                        );
                    }
                }
                $team_competitors1 = $this->syncDataTeamCompetitors($team_competitors, $event_team->id);
            }
            DB::commit();
            return 1;
        } catch (\Exception $e) {
            DB::rollBack();
            $this->errorResponseSystem();
        }
    }

    public function syncDataTeamCompetitors($team_competitors, $event_team_id)
    {
        DB::beginTransaction();
        try {
            foreach ($team_competitors as $tc) {
                DB::table('event_team_competitors')->updateOrInsert([
                    "event_team_id" => $event_team_id,
                    "competitor_id" => $tc->id,
                ]);
            }
            DB::commit();
            return 1;
        } catch (\Exception $e) {
            DB::rollBack();
            $this->errorResponseSystem();
        }
    }
}
